<?php

/**
 * Implements hook_install().
 *
 * Perform actions to set up the contact feature.
 */
function campuscms_feature_contact_install() {
  // Change the url of the contact form.
  $alias = array(
    'source' => 'contact',
    'alias' => 'contact-us',
  );

  path_save($alias);
  
  drupal_set_message(t('Please go to @url to configure your contact form', array('@url' => l('contact configuration page', 'admin/structure/contact'))));
}